export enum ConfigurationKeys {
  PORT = 'PORT',
  HOST = 'HOST',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  CONNECTION_LIMIT = 'CONNECTION_LIMIT',
}